version: '3'
services:
  api:
    environment:
      - NODE_ENV=production
      - JWT_PRIVATE_KEY="ari-ganteng-bet"
      - DB_USERNAME="postgres"
      - DB_PASSWORD="postgres"
      - DB_DATABASE="db_cbs_simulator"
      - DB_HOST="localhost"
      - DB_DIALECT="postgres"
      - DB_PORT="5432"
      - DB_LOGGING=false
    image: cbs-simulator
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: cbs-simulator
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
